source 'https://ruby.taobao.org'

gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-assetpack"
gem "haml"
gem "sass"
gem "coffee-script"
gem "yui-compressor"
gem "pry"
gem "knowledge-net-plan-store", :path => "../"
